language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
after_script:
  - mvn test jacoco:report coveralls:report -Dcoveralls.token=$coveralls_repo_token

matrix:
  allow_failures:
  - jdk: openjdk8
  - jdk: openjdk9
